### ISSUE TITLE
Using Proxy ?

### ISSUE THREAD

**Issue by matlink** [floyd-fuh/tiny-mitm-proxy#1]
What if the system requires a proxy to go out ? Is that script easily adaptable to match a such condition ?

**Comment by floyd-fuh** [comment]
This is a transparent MITM setup on the TCP layer, if the client sends Proxy connection requests that's fine and we will simply see the proxy connection requests first (written to files). But depending on what kind of proxy you are talking about, this is the wrong tool anyway. If you are talking about HTTP traffic, you should better use burp or another HTTP proxy than this.

In other words: this tool works one layer lower in the OSI model.
